### ISSUE TITLE
`ndx.prod()` fails for `float64`

### ISSUE THREAD

**Issue by MatejUrbanQC** [Quantco/ndonnx#20]
The function is using `ReduceProd` onnx operator, which is missing a `float64` version in `onnxruntime`.
## Code to reproduce:
```Py
import ndonnx as ndx
ndx.prod(ndx.asarray([2.,2.]))
```
## Error:
```
2024-07-19 16:10:02.392185 [W:onnxruntime:, constant_folding.cc:269 ApplyImpl] Could not find a CPU kernel and hence can't constant fold ReduceProd node 'ReduceProd_0'
2024-07-19 16:10:02.392271 [W:onnxruntime:, constant_folding.cc:269 ApplyImpl] Could not find a CPU kernel and hence can't constant fold ReduceProd node 'ReduceProd_0'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matejurban/ndonnx/ndonnx/_funcs.py", line 848, in prod
    out := x.dtype._ops.prod(x, dtype=dtype, axis=axis, keepdims=keepdims)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/ndonnx/_core/_impl.py", line 728, in prod
    out = _via_i64_f64(
          ^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/ndonnx/_core/_impl.py", line 1029, in _via_i64_f64
    return _variadic_op(arrays, fn, via_dtype, cast_return)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/ndonnx/_core/_impl.py", line 929, in _variadic_op
    values = _via_dtype(op, via_dtype, data, cast_return=cast_return)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/ndonnx/_core/_impl.py", line 990, in _via_dtype
    out_value = _from_corearray(fn(*[value._core() for value in values]))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/ndonnx/_core/_impl.py", line 729, in <lambda>
    lambda x: opx.reduce_prod(
              ^^^^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/ndonnx/_propagation.py", line 34, in wrapper
    return _eager_propagate_with_custom_operators(None)(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/ndonnx/_propagation.py", line 48, in wrapper
    prediction = _propagate_helper(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/ndonnx/_propagation.py", line 198, in _propagate_helper
    sess = ort.InferenceSession(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matejurban/ndonnx/.pixi/envs/default/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/matejurban/ndonnx/.pixi/envs/default/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ReduceProd(18) node with name 'ReduceProd_0'
```

**Comment by adityagoel4512** [comment]
Thanks for the issue. While technically `ReduceProd` should have `float64` input and output pairs as per the [ONNX standard](https://github.com/onnx/onnx/blob/main/docs/Operators.md#ReduceProd), the kernel has no double implementation in ORT as you point out. There was some discussion about why ORT doesn't seem to want to implement the entire standard [here](https://github.com/microsoft/onnxruntime/issues/15397).

In principle ndonnx should care only about what the standard says, but practically speaking people care about what onnxruntime can run today (hence some of the `i64/f64` gymnastics in the code base). The immediate fix is to make the floating types cast to `f32` instead (excluding any casts that may lose precision, e.g. f64 -> f32).
